
# Initial parameter values
# EA
GENOTYPE_POOL_SIZE = 150
ADULT_POOL_SIZE = 150
ELITISM = 8
ADULT_SELECTION_PROTOCOL = 1
PARENT_SELECTION_PROTOCOL = 3
MUTATION_PROTOCOL = 1
CROSSOVER_RATE = 0.85  # When two parents have a match, they have a X% chance of being recombined.
# When they are not combined they are simply copied (with mutations)
POINTS_OF_CROSSOVER = 1
MUTATION_RATE = 0.75
SYMBOL_SET_SIZE = 256
TOURNAMENT_SLIP_THROUGH_PROBABILITY = 0.35
TOURNAMENT_SIZE = 30
INITIAL_TEMPERATURE = 100
MAX_GENERATIONS = 35

# GUI
SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 900
GRID_OFFSET = 20
WORLD_WIDTH = 30
WORLD_HEIGHT = 15
INITIAL_DELAY = 300

# Problem specific
NR_OF_SCENARIOS = 1
SCENARIO_PROTOCOL = 2
TIMESTEPS = 600
AGENT_SIZE = 5
BEER_MAX_SIZE = 6
AGENT_TYPE = 3
AGENT_MAX_NR_OF_STEPS = 4
BEER_MAX_WANTED_SIZE = 4
PULL_THRESHOLD = 0.9

# ANN
INPUT_NODES = 5
OUTPUT_NODES = 9
ONE_HOT_OUTPUT = False
RECURENCE = True
WEIGHT_MIN = -5
WEIGHT_MAX = 5
BIAS_MIN = -10
BIAS_MAX = 0
GAINS_MIN = 1
GAINS_MAX = 5
TIME_CONSTANT_MIN = 1
TIME_CONSTANT_MAX = 2

# Feature extraction
CENTERED_NODE = False
FULL_NODE = False

# Debug
MULTIPROCESSING = True


