
# Initial parameter values
GENOTYPE_POOL_SIZE = 100
ADULT_POOL_SIZE = 100
ELITISM = 1
ADULT_SELECTION_PROTOCOL = 3
PARENT_SELECTION_PROTOCOL = 3
MUTATION_PROTOCOL = 1
CROSSOVER_RATE = 0.85  # When two parents have a match, they have a X% chance of being recombined.
# When they are not combined they are simply copied (with mutations)
POINTS_OF_CROSSOVER = 1
MUTATION_RATE = 0.35
SYMBOL_SET_SIZE = 10
TOURNAMENT_SLIP_THROUGH_PROBABILITY = 0.1
TOURNAMENT_SIZE = 10
INITIAL_TEMPERATURE = 100
MAX_GENERATIONS = 100

FLATLAND_WIDTH = 10
FLATLAND_HEIGHT = 10
FOOD_PROBABILITY = 0.3
POISON_PROBABILITY = 0.3
TIMESTEPS = 60
NR_OF_SCENARIOS = 5
SCENARIO_PROTOCOL = 2
INPUT_NODES = 6
OUTPUT_NODES = 3

GRID_OFFSET = 20
SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 900
